#!/usr/bin/env python3
"""Extract Logitech device thumbnails from Options+ depot on macOS.

Reads devices.json to build a modelId -> thumbnail mapping,
copies real PNG files to public/devices/thumbnails/,
and generates src/data/device-catalog.ts.
"""

import json
import os
import re
import shutil
import struct
from pathlib import Path

DEPOT_BASE = "/Library/Application Support/Logi/LogiOptionsPlus/depots/700276"
THUMB_DIR = os.path.join(DEPOT_BASE, "logioptionsplus/thumbnails")
DEVICES_JSON = "/Library/Application Support/Logi/LogiOptionsPlus/devices.json"

SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent
OUT_THUMBS = PROJECT_ROOT / "public" / "devices" / "thumbnails"
OUT_HIRES = PROJECT_ROOT / "public" / "devices" / "hires"
OUT_TS = PROJECT_ROOT / "src" / "data" / "device-catalog.ts"


def is_real_png(path: str) -> bool:
    """Check if file starts with PNG magic bytes."""
    try:
        with open(path, "rb") as f:
            return f.read(8) == b"\x89PNG\r\n\x1a\n"
    except (OSError, IOError):
        return False


def extract_thumbnails(devices: list) -> dict:
    """Extract thumbnail mapping and copy real PNGs."""
    catalog = {}
    seen_depots = set()
    copied = 0
    skipped = 0

    for device in devices:
        depot = device.get("depot", "")
        display_name = device.get("displayName", "Unknown")
        model_id = device.get("modelId", "")

        if depot in seen_depots:
            continue
        seen_depots.add(depot)

        # Find all pipeline:// thumbnail references
        text = json.dumps(device)
        thumb_refs = re.findall(r"pipeline://logioptionsplus/thumbnails/([^\"]+)", text)

        # Base thumbnail (no _ext suffix)
        base_thumbs = [t for t in thumb_refs if "_ext" not in t]
        ext_thumbs = [t for t in thumb_refs if "_ext" in t]

        base_thumb = base_thumbs[0] if base_thumbs else None
        thumb_path = None

        if base_thumb:
            src = os.path.join(THUMB_DIR, base_thumb)
            if os.path.isfile(src) and is_real_png(src):
                dst = OUT_THUMBS / base_thumb
                shutil.copy2(src, dst)
                thumb_path = f"/devices/thumbnails/{base_thumb}"
                copied += 1
            else:
                skipped += 1

        # Copy ext variants too
        variants = []
        for ext in ext_thumbs:
            src = os.path.join(THUMB_DIR, ext)
            if os.path.isfile(src) and is_real_png(src):
                dst = OUT_THUMBS / ext
                shutil.copy2(src, dst)
                # Extract variant modelId from device data
                variant_model = ext.replace(".png", "")
                variants.append({
                    "modelId": variant_model,
                    "thumbnail": f"/devices/thumbnails/{ext}",
                })
                copied += 1

        catalog[model_id] = {
            "modelId": model_id,
            "displayName": display_name,
            "depot": depot,
            "thumbnail": thumb_path,
            "variants": variants,
        }

    print(f"Copied {copied} thumbnails, skipped {skipped} encrypted")
    return catalog


def extract_hires(devices: list):
    """Copy high-res images from connected device depots."""
    copied = 0
    for device in devices:
        depot = device.get("depot", "")
        depot_path = os.path.join(DEPOT_BASE, depot)
        if not os.path.isdir(depot_path):
            continue

        # Look for front_core.png or front.png
        has_images = False
        for fname in os.listdir(depot_path):
            if fname.endswith(".png") and is_real_png(os.path.join(depot_path, fname)):
                has_images = True
                break

        if has_images:
            out_dir = OUT_HIRES / depot
            out_dir.mkdir(parents=True, exist_ok=True)
            for fname in os.listdir(depot_path):
                src = os.path.join(depot_path, fname)
                if fname.endswith(".png") and is_real_png(src):
                    shutil.copy2(src, out_dir / fname)
                    copied += 1

    print(f"Copied {copied} high-res device images")


def generate_typescript(catalog: dict):
    """Generate src/data/device-catalog.ts."""
    OUT_TS.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "// Auto-generated by scripts/extract-device-images.py",
        "// Do not edit manually.",
        "",
        "export interface DeviceCatalogEntry {",
        "  modelId: string;",
        "  displayName: string;",
        "  depot: string;",
        "  thumbnail: string | null;",
        "  variants: { modelId: string; thumbnail: string | null }[];",
        "}",
        "",
        "export const DEVICE_CATALOG: Record<string, DeviceCatalogEntry> = ",
    ]

    json_str = json.dumps(catalog, indent=2, ensure_ascii=False)
    lines.append(json_str + ";")
    lines.append("")

    OUT_TS.write_text("\n".join(lines))
    print(f"Generated {OUT_TS} with {len(catalog)} devices")


def main():
    if not os.path.isfile(DEVICES_JSON):
        print(f"ERROR: {DEVICES_JSON} not found. Is Logi Options+ installed?")
        return

    OUT_THUMBS.mkdir(parents=True, exist_ok=True)
    OUT_HIRES.mkdir(parents=True, exist_ok=True)

    with open(DEVICES_JSON) as f:
        data = json.load(f)

    devices = data.get("devices", [])
    print(f"Found {len(devices)} device entries in devices.json")

    catalog = extract_thumbnails(devices)
    extract_hires(devices)
    generate_typescript(catalog)


if __name__ == "__main__":
    main()
