// Auto-generated by scripts/extract-device-images.py
// Do not edit manually.

export interface DeviceCatalogEntry {
  modelId: string;
  displayName: string;
  depot: string;
  thumbnail: string | null;
  variants: { modelId: string; thumbnail: string | null }[];
}

export const DEVICE_CATALOG: Record<string, DeviceCatalogEntry> = 
{
  "6b023": {
    "modelId": "6b023",
    "displayName": "MX Master 3",
    "depot": "mx_master_3",
    "thumbnail": "/devices/thumbnails/mx_master_3.png",
    "variants": [
      {
        "modelId": "mx_master_3_ext1",
        "thumbnail": "/devices/thumbnails/mx_master_3_ext1.png"
      },
      {
        "modelId": "mx_master_3_ext2",
        "thumbnail": "/devices/thumbnails/mx_master_3_ext2.png"
      },
      {
        "modelId": "mx_master_3_ext3",
        "thumbnail": "/devices/thumbnails/mx_master_3_ext3.png"
      },
      {
        "modelId": "mx_master_3_ext1",
        "thumbnail": "/devices/thumbnails/mx_master_3_ext1.png"
      },
      {
        "modelId": "mx_master_3_ext2",
        "thumbnail": "/devices/thumbnails/mx_master_3_ext2.png"
      },
      {
        "modelId": "mx_master_3_ext3",
        "thumbnail": "/devices/thumbnails/mx_master_3_ext3.png"
      }
    ]
  },
  "6b35b": {
    "modelId": "6b35b",
    "displayName": "MX Keys",
    "depot": "mx_keys",
    "thumbnail": "/devices/thumbnails/mx_keys.png",
    "variants": [
      {
        "modelId": "mx_keys_ext1",
        "thumbnail": "/devices/thumbnails/mx_keys_ext1.png"
      },
      {
        "modelId": "mx_keys_ext1",
        "thumbnail": "/devices/thumbnails/mx_keys_ext1.png"
      }
    ]
  },
  "6b361": {
    "modelId": "6b361",
    "displayName": "MX Keys for Mac",
    "depot": "mx_keys_mac",
    "thumbnail": "/devices/thumbnails/mx_keys_mac.png",
    "variants": []
  },
  "1b342": {
    "modelId": "1b342",
    "displayName": "K380",
    "depot": "k380",
    "thumbnail": "/devices/thumbnails/k380.png",
    "variants": []
  },
  "1b362": {
    "modelId": "1b362",
    "displayName": "K380 for Mac",
    "depot": "k380_mac",
    "thumbnail": "/devices/thumbnails/k380_mac.png",
    "variants": []
  },
  "6b025": {
    "modelId": "6b025",
    "displayName": "MX Anywhere 3",
    "depot": "mx_anywhere_3",
    "thumbnail": "/devices/thumbnails/mx_anywhere_3.png",
    "variants": [
      {
        "modelId": "mx_anywhere_3_ext1",
        "thumbnail": "/devices/thumbnails/mx_anywhere_3_ext1.png"
      },
      {
        "modelId": "mx_anywhere_3_ext2",
        "thumbnail": "/devices/thumbnails/mx_anywhere_3_ext2.png"
      },
      {
        "modelId": "mx_anywhere_3_ext3",
        "thumbnail": "/devices/thumbnails/mx_anywhere_3_ext3.png"
      },
      {
        "modelId": "mx_anywhere_3_ext4",
        "thumbnail": "/devices/thumbnails/mx_anywhere_3_ext4.png"
      },
      {
        "modelId": "mx_anywhere_3_ext1",
        "thumbnail": "/devices/thumbnails/mx_anywhere_3_ext1.png"
      },
      {
        "modelId": "mx_anywhere_3_ext2",
        "thumbnail": "/devices/thumbnails/mx_anywhere_3_ext2.png"
      },
      {
        "modelId": "mx_anywhere_3_ext3",
        "thumbnail": "/devices/thumbnails/mx_anywhere_3_ext3.png"
      },
      {
        "modelId": "mx_anywhere_3_ext4",
        "thumbnail": "/devices/thumbnails/mx_anywhere_3_ext4.png"
      }
    ]
  },
  "44057": {
    "modelId": "44057",
    "displayName": "M275/M280/M320/M330/M331",
    "depot": "m280",
    "thumbnail": "/devices/thumbnails/m280.png",
    "variants": []
  },
  "2b02b": {
    "modelId": "2b02b",
    "displayName": "Signature M550 L",
    "depot": "signature_m550",
    "thumbnail": "/devices/thumbnails/signature_m550.png",
    "variants": [
      {
        "modelId": "signature_m550_ext1",
        "thumbnail": "/devices/thumbnails/signature_m550_ext1.png"
      },
      {
        "modelId": "signature_m550_ext2",
        "thumbnail": "/devices/thumbnails/signature_m550_ext2.png"
      },
      {
        "modelId": "signature_m550_ext1",
        "thumbnail": "/devices/thumbnails/signature_m550_ext1.png"
      },
      {
        "modelId": "signature_m550_ext2",
        "thumbnail": "/devices/thumbnails/signature_m550_ext2.png"
      }
    ]
  },
  "2b02a": {
    "modelId": "2b02a",
    "displayName": "Signature M650 L",
    "depot": "signature_m650",
    "thumbnail": "/devices/thumbnails/signature_m650.png",
    "variants": [
      {
        "modelId": "signature_m650_ext1",
        "thumbnail": "/devices/thumbnails/signature_m650_ext1.png"
      },
      {
        "modelId": "signature_m650_ext2",
        "thumbnail": "/devices/thumbnails/signature_m650_ext2.png"
      },
      {
        "modelId": "signature_m650_ext3",
        "thumbnail": "/devices/thumbnails/signature_m650_ext3.png"
      },
      {
        "modelId": "signature_m650_ext6",
        "thumbnail": "/devices/thumbnails/signature_m650_ext6.png"
      },
      {
        "modelId": "signature_m650_ext7",
        "thumbnail": "/devices/thumbnails/signature_m650_ext7.png"
      },
      {
        "modelId": "signature_m650_ext1",
        "thumbnail": "/devices/thumbnails/signature_m650_ext1.png"
      },
      {
        "modelId": "signature_m650_ext2",
        "thumbnail": "/devices/thumbnails/signature_m650_ext2.png"
      },
      {
        "modelId": "signature_m650_ext3",
        "thumbnail": "/devices/thumbnails/signature_m650_ext3.png"
      }
    ]
  },
  "2b032": {
    "modelId": "2b032",
    "displayName": "Signature M650 For Business",
    "depot": "signature_m650_for_business",
    "thumbnail": "/devices/thumbnails/signature_m650_for_business.png",
    "variants": [
      {
        "modelId": "signature_m650_for_business_ext1",
        "thumbnail": "/devices/thumbnails/signature_m650_for_business_ext1.png"
      },
      {
        "modelId": "signature_m650_for_business_ext1",
        "thumbnail": "/devices/thumbnails/signature_m650_for_business_ext1.png"
      }
    ]
  },
  "2b02c": {
    "modelId": "2b02c",
    "displayName": "Signature Plus M750 L",
    "depot": "signature_m750",
    "thumbnail": "/devices/thumbnails/signature_m750.png",
    "variants": [
      {
        "modelId": "signature_m750_ext1",
        "thumbnail": "/devices/thumbnails/signature_m750_ext1.png"
      },
      {
        "modelId": "signature_m750_ext1",
        "thumbnail": "/devices/thumbnails/signature_m750_ext1.png"
      },
      {
        "modelId": "signature_m750_ext4",
        "thumbnail": "/devices/thumbnails/signature_m750_ext4.png"
      },
      {
        "modelId": "signature_m750_ext4",
        "thumbnail": "/devices/thumbnails/signature_m750_ext4.png"
      }
    ]
  },
  "2b028": {
    "modelId": "2b028",
    "displayName": "MX Master 3 B",
    "depot": "mx_master_3_for_business",
    "thumbnail": "/devices/thumbnails/mx_master_3_for_business.png",
    "variants": []
  },
  "2b363": {
    "modelId": "2b363",
    "displayName": "MX Keys B",
    "depot": "mx_keys_for_business",
    "thumbnail": "/devices/thumbnails/mx_keys_for_business.png",
    "variants": []
  },
  "2b02d": {
    "modelId": "2b02d",
    "displayName": "MX Anywhere 3 for Business",
    "depot": "mx_anywhere_3_for_business",
    "thumbnail": "/devices/thumbnails/mx_anywhere_3_for_business.png",
    "variants": [
      {
        "modelId": "mx_anywhere_3_for_business_ext1",
        "thumbnail": "/devices/thumbnails/mx_anywhere_3_for_business_ext1.png"
      }
    ]
  },
  "6b01d": {
    "modelId": "6b01d",
    "displayName": "MX Ergo",
    "depot": "mx_ergo",
    "thumbnail": "/devices/thumbnails/mx_ergo.png",
    "variants": []
  },
  "2b369": {
    "modelId": "2b369",
    "displayName": "MX Keys Mini",
    "depot": "mx_keys_mini",
    "thumbnail": "/devices/thumbnails/mx_keys_mini.png",
    "variants": [
      {
        "modelId": "mx_keys_mini_ext1",
        "thumbnail": "/devices/thumbnails/mx_keys_mini_ext1.png"
      },
      {
        "modelId": "mx_keys_mini_ext2",
        "thumbnail": "/devices/thumbnails/mx_keys_mini_ext2.png"
      },
      {
        "modelId": "mx_keys_mini_ext3",
        "thumbnail": "/devices/thumbnails/mx_keys_mini_ext3.png"
      },
      {
        "modelId": "mx_keys_mini_ext1",
        "thumbnail": "/devices/thumbnails/mx_keys_mini_ext1.png"
      },
      {
        "modelId": "mx_keys_mini_ext2",
        "thumbnail": "/devices/thumbnails/mx_keys_mini_ext2.png"
      }
    ]
  },
  "2b36a": {
    "modelId": "2b36a",
    "displayName": "MX Keys Mini for Mac",
    "depot": "mx_keys_mini_mac",
    "thumbnail": "/devices/thumbnails/mx_keys_mini_mac.png",
    "variants": [
      {
        "modelId": "mx_keys_mini_mac_ext1",
        "thumbnail": "/devices/thumbnails/mx_keys_mini_mac_ext1.png"
      }
    ]
  },
  "2b36e": {
    "modelId": "2b36e",
    "displayName": "MX Keys Mini for Business",
    "depot": "mx_keys_mini_for_business",
    "thumbnail": "/devices/thumbnails/mx_keys_mini_for_business.png",
    "variants": [
      {
        "modelId": "mx_keys_mini_for_business_ext1",
        "thumbnail": "/devices/thumbnails/mx_keys_mini_for_business_ext1.png"
      }
    ]
  },
  "c52b": {
    "modelId": "c52b",
    "displayName": "Logi Unifying receiver",
    "depot": "c52b",
    "thumbnail": null,
    "variants": []
  },
  "c548": {
    "modelId": "c548",
    "displayName": "Logi Bolt USB-A receiver",
    "depot": "c548",
    "thumbnail": null,
    "variants": []
  },
  "c52f": {
    "modelId": "c52f",
    "displayName": "Logi USB receiver",
    "depot": "c52f",
    "thumbnail": null,
    "variants": []
  },
  "c534": {
    "modelId": "c534",
    "displayName": "Logi USB receiver",
    "depot": "c534",
    "thumbnail": null,
    "variants": []
  },
  "2b031": {
    "modelId": "2b031",
    "displayName": "LIFT",
    "depot": "mx_vertical_mini",
    "thumbnail": "/devices/thumbnails/mx_vertical_mini.png",
    "variants": [
      {
        "modelId": "mx_vertical_mini_ext1",
        "thumbnail": "/devices/thumbnails/mx_vertical_mini_ext1.png"
      },
      {
        "modelId": "mx_vertical_mini_ext2",
        "thumbnail": "/devices/thumbnails/mx_vertical_mini_ext2.png"
      },
      {
        "modelId": "mx_vertical_mini_ext3",
        "thumbnail": "/devices/thumbnails/mx_vertical_mini_ext3.png"
      },
      {
        "modelId": "mx_vertical_mini_ext2",
        "thumbnail": "/devices/thumbnails/mx_vertical_mini_ext2.png"
      },
      {
        "modelId": "mx_vertical_mini_ext8",
        "thumbnail": "/devices/thumbnails/mx_vertical_mini_ext8.png"
      },
      {
        "modelId": "mx_vertical_mini_ext2",
        "thumbnail": "/devices/thumbnails/mx_vertical_mini_ext2.png"
      },
      {
        "modelId": "mx_vertical_mini_ext3",
        "thumbnail": "/devices/thumbnails/mx_vertical_mini_ext3.png"
      }
    ]
  },
  "2b033": {
    "modelId": "2b033",
    "displayName": "LIFT for Business",
    "depot": "mx_vertical_mini_for_business",
    "thumbnail": "/devices/thumbnails/mx_vertical_mini.png",
    "variants": [
      {
        "modelId": "mx_vertical_mini_ext1",
        "thumbnail": "/devices/thumbnails/mx_vertical_mini_ext1.png"
      },
      {
        "modelId": "mx_vertical_mini_ext2",
        "thumbnail": "/devices/thumbnails/mx_vertical_mini_ext2.png"
      }
    ]
  },
  "2b034": {
    "modelId": "2b034",
    "displayName": "MX Master 3S",
    "depot": "mx_master_3s",
    "thumbnail": "/devices/thumbnails/mx_master_3s.png",
    "variants": [
      {
        "modelId": "mx_master_3s_ext1",
        "thumbnail": "/devices/thumbnails/mx_master_3s_ext1.png"
      },
      {
        "modelId": "mx_master_3s_ext2",
        "thumbnail": "/devices/thumbnails/mx_master_3s_ext2.png"
      },
      {
        "modelId": "mx_master_3s_ext1",
        "thumbnail": "/devices/thumbnails/mx_master_3s_ext1.png"
      },
      {
        "modelId": "mx_master_3s_ext4",
        "thumbnail": "/devices/thumbnails/mx_master_3s_ext4.png"
      },
      {
        "modelId": "mx_master_3s_ext10",
        "thumbnail": "/devices/thumbnails/mx_master_3s_ext10.png"
      },
      {
        "modelId": "mx_master_3s_ext12",
        "thumbnail": "/devices/thumbnails/mx_master_3s_ext12.png"
      },
      {
        "modelId": "mx_master_3s_ext12",
        "thumbnail": "/devices/thumbnails/mx_master_3s_ext12.png"
      },
      {
        "modelId": "mx_master_3s_ext10",
        "thumbnail": "/devices/thumbnails/mx_master_3s_ext10.png"
      }
    ]
  },
  "2b035": {
    "modelId": "2b035",
    "displayName": "MX Master 3s for Business",
    "depot": "mx_master_3s_for_business",
    "thumbnail": "/devices/thumbnails/mx_master_3s_for_business.png",
    "variants": [
      {
        "modelId": "mx_master_3s_for_business_ext10",
        "thumbnail": "/devices/thumbnails/mx_master_3s_for_business_ext10.png"
      }
    ]
  },
  "2b372": {
    "modelId": "2b372",
    "displayName": "Signature K855",
    "depot": "signature_k855",
    "thumbnail": "/devices/thumbnails/signature_k855.png",
    "variants": [
      {
        "modelId": "signature_k855_ext1",
        "thumbnail": "/devices/thumbnails/signature_k855_ext1.png"
      },
      {
        "modelId": "signature_k855_ext2",
        "thumbnail": "/devices/thumbnails/signature_k855_ext2.png"
      },
      {
        "modelId": "signature_k855_ext3",
        "thumbnail": "/devices/thumbnails/signature_k855_ext3.png"
      },
      {
        "modelId": "signature_k855_ext1",
        "thumbnail": "/devices/thumbnails/signature_k855_ext1.png"
      },
      {
        "modelId": "signature_k855_ext2",
        "thumbnail": "/devices/thumbnails/signature_k855_ext2.png"
      },
      {
        "modelId": "signature_k855_ext3",
        "thumbnail": "/devices/thumbnails/signature_k855_ext3.png"
      }
    ]
  },
  "2b367": {
    "modelId": "2b367",
    "displayName": "MX Mechanical Mini",
    "depot": "mx_mechanical_mini",
    "thumbnail": "/devices/thumbnails/mx_mechanical_mini.png",
    "variants": []
  },
  "2b36d": {
    "modelId": "2b36d",
    "displayName": "MX Mechanical Mini for Mac",
    "depot": "mx_mechanical_mini_mac",
    "thumbnail": "/devices/thumbnails/mx_mechanical_mini_mac.png",
    "variants": [
      {
        "modelId": "mx_mechanical_mini_mac_ext1",
        "thumbnail": "/devices/thumbnails/mx_mechanical_mini_mac_ext1.png"
      },
      {
        "modelId": "mx_mechanical_mini_mac_ext1",
        "thumbnail": "/devices/thumbnails/mx_mechanical_mini_mac_ext1.png"
      }
    ]
  },
  "2b366": {
    "modelId": "2b366",
    "displayName": "MX Mechanical",
    "depot": "mx_mechanical",
    "thumbnail": "/devices/thumbnails/mx_mechanical.png",
    "variants": []
  },
  "2b365": {
    "modelId": "2b365",
    "displayName": "POP Keys",
    "depot": "pop_keys",
    "thumbnail": "/devices/thumbnails/pop_keys.png",
    "variants": [
      {
        "modelId": "pop_keys_ext1",
        "thumbnail": "/devices/thumbnails/pop_keys_ext1.png"
      },
      {
        "modelId": "pop_keys_ext2",
        "thumbnail": "/devices/thumbnails/pop_keys_ext2.png"
      },
      {
        "modelId": "pop_keys_ext3",
        "thumbnail": "/devices/thumbnails/pop_keys_ext3.png"
      },
      {
        "modelId": "pop_keys_ext4",
        "thumbnail": "/devices/thumbnails/pop_keys_ext4.png"
      },
      {
        "modelId": "pop_keys_ext5",
        "thumbnail": "/devices/thumbnails/pop_keys_ext5.png"
      },
      {
        "modelId": "pop_keys_ext1",
        "thumbnail": "/devices/thumbnails/pop_keys_ext1.png"
      },
      {
        "modelId": "pop_keys_ext2",
        "thumbnail": "/devices/thumbnails/pop_keys_ext2.png"
      }
    ]
  },
  "2b030": {
    "modelId": "2b030",
    "displayName": "POP Mouse",
    "depot": "pop_mouse",
    "thumbnail": "/devices/thumbnails/pop_mouse.png",
    "variants": [
      {
        "modelId": "pop_mouse_ext1",
        "thumbnail": "/devices/thumbnails/pop_mouse_ext1.png"
      },
      {
        "modelId": "pop_mouse_ext2",
        "thumbnail": "/devices/thumbnails/pop_mouse_ext2.png"
      },
      {
        "modelId": "pop_mouse_ext3",
        "thumbnail": "/devices/thumbnails/pop_mouse_ext3.png"
      },
      {
        "modelId": "pop_mouse_ext4",
        "thumbnail": "/devices/thumbnails/pop_mouse_ext4.png"
      },
      {
        "modelId": "pop_mouse_ext5",
        "thumbnail": "/devices/thumbnails/pop_mouse_ext5.png"
      },
      {
        "modelId": "pop_mouse_ext6",
        "thumbnail": "/devices/thumbnails/pop_mouse_ext6.png"
      },
      {
        "modelId": "pop_mouse_ext7",
        "thumbnail": "/devices/thumbnails/pop_mouse_ext7.png"
      },
      {
        "modelId": "pop_mouse_ext8",
        "thumbnail": "/devices/thumbnails/pop_mouse_ext8.png"
      },
      {
        "modelId": "pop_mouse_ext9",
        "thumbnail": "/devices/thumbnails/pop_mouse_ext9.png"
      }
    ]
  },
  "2b36f": {
    "modelId": "2b36f",
    "displayName": "Signature K650",
    "depot": "k650",
    "thumbnail": "/devices/thumbnails/k650_for_business.png",
    "variants": [
      {
        "modelId": "k650_for_business_ext1",
        "thumbnail": "/devices/thumbnails/k650_for_business_ext1.png"
      },
      {
        "modelId": "k650_for_business_ext1",
        "thumbnail": "/devices/thumbnails/k650_for_business_ext1.png"
      }
    ]
  },
  "2b370": {
    "modelId": "2b370",
    "displayName": "Signature K650 for Business",
    "depot": "k650_for_business",
    "thumbnail": "/devices/thumbnails/k650_for_business.png",
    "variants": [
      {
        "modelId": "k650_for_business_ext1",
        "thumbnail": "/devices/thumbnails/k650_for_business_ext1.png"
      },
      {
        "modelId": "k650_for_business_ext1",
        "thumbnail": "/devices/thumbnails/k650_for_business_ext1.png"
      }
    ]
  },
  "44051": {
    "modelId": "44051",
    "displayName": "M510",
    "depot": "m510",
    "thumbnail": "/devices/thumbnails/m510.png",
    "variants": []
  },
  "4076": {
    "modelId": "4076",
    "displayName": "K540/K545",
    "depot": "k545",
    "thumbnail": "/devices/thumbnails/k545.png",
    "variants": []
  },
  "44055": {
    "modelId": "44055",
    "displayName": "Wireless Mouse",
    "depot": "m310",
    "thumbnail": "/devices/thumbnails/rom_mice.png",
    "variants": []
  },
  "6b359": {
    "modelId": "6b359",
    "displayName": "Ergo K860",
    "depot": "ergo_k860",
    "thumbnail": "/devices/thumbnails/ergo_k860.png",
    "variants": []
  },
  "2b364": {
    "modelId": "2b364",
    "displayName": "Ergo K860 for Business",
    "depot": "ergo_k860_for_business",
    "thumbnail": "/devices/thumbnails/ergo_k860_for_business.png",
    "variants": []
  },
  "6b027": {
    "modelId": "6b027",
    "displayName": "Ergo M575",
    "depot": "m575",
    "thumbnail": "/devices/thumbnails/m575.png",
    "variants": [
      {
        "modelId": "m575_ext1",
        "thumbnail": "/devices/thumbnails/m575_ext1.png"
      },
      {
        "modelId": "m575_ext2",
        "thumbnail": "/devices/thumbnails/m575_ext2.png"
      },
      {
        "modelId": "m575_ext1",
        "thumbnail": "/devices/thumbnails/m575_ext1.png"
      },
      {
        "modelId": "m575_ext1",
        "thumbnail": "/devices/thumbnails/m575_ext1.png"
      },
      {
        "modelId": "m575_ext2",
        "thumbnail": "/devices/thumbnails/m575_ext2.png"
      },
      {
        "modelId": "m575_ext1",
        "thumbnail": "/devices/thumbnails/m575_ext1.png"
      }
    ]
  },
  "2b02f": {
    "modelId": "2b02f",
    "displayName": "Ergo M575 for Business",
    "depot": "m575_for_business",
    "thumbnail": "/devices/thumbnails/m575.png",
    "variants": [
      {
        "modelId": "m575_ext2",
        "thumbnail": "/devices/thumbnails/m575_ext2.png"
      }
    ]
  },
  "eb020": {
    "modelId": "eb020",
    "displayName": "MX Vertical",
    "depot": "mx_vertical",
    "thumbnail": "/devices/thumbnails/mx_vertical.png",
    "variants": []
  },
  "6b015": {
    "modelId": "6b015",
    "displayName": "M720 TRIATHLON",
    "depot": "m720_triathlon",
    "thumbnail": "/devices/thumbnails/m720_triathlon.png",
    "variants": []
  },
  "6b34d": {
    "modelId": "6b34d",
    "displayName": "K850",
    "depot": "k850",
    "thumbnail": "/devices/thumbnails/k850.png",
    "variants": []
  },
  "4091": {
    "modelId": "4091",
    "displayName": "Wireless Mouse",
    "depot": "m185",
    "thumbnail": "/devices/thumbnails/rom_mice.png",
    "variants": []
  },
  "4054": {
    "modelId": "4054",
    "displayName": "Wireless Mouse",
    "depot": "m187",
    "thumbnail": "/devices/thumbnails/rom_mice.png",
    "variants": []
  },
  "6b35a": {
    "modelId": "6b35a",
    "displayName": "K580/K585",
    "depot": "k580",
    "thumbnail": "/devices/thumbnails/k580.png",
    "variants": [
      {
        "modelId": "k580_ext1",
        "thumbnail": "/devices/thumbnails/k580_ext1.png"
      },
      {
        "modelId": "k580_ext2",
        "thumbnail": "/devices/thumbnails/k580_ext2.png"
      },
      {
        "modelId": "k580_ext1",
        "thumbnail": "/devices/thumbnails/k580_ext1.png"
      },
      {
        "modelId": "k580_ext2",
        "thumbnail": "/devices/thumbnails/k580_ext2.png"
      }
    ]
  },
  "6b350": {
    "modelId": "6b350",
    "displayName": "Craft",
    "depot": "craft",
    "thumbnail": "/devices/thumbnails/craft.png",
    "variants": []
  },
  "6b013": {
    "modelId": "6b013",
    "displayName": "MX Anywhere 2",
    "depot": "mx_anywhere_2",
    "thumbnail": "/devices/thumbnails/mx_anywhere_2.png",
    "variants": []
  },
  "6b018": {
    "modelId": "6b018",
    "displayName": "MX Anywhere 2",
    "depot": "mx_anywhere_2_restage",
    "thumbnail": "/devices/thumbnails/mx_anywhere_2.png",
    "variants": [
      {
        "modelId": "mx_anywhere_2_ext1",
        "thumbnail": "/devices/thumbnails/mx_anywhere_2_ext1.png"
      },
      {
        "modelId": "mx_anywhere_2_ext2",
        "thumbnail": "/devices/thumbnails/mx_anywhere_2_ext2.png"
      },
      {
        "modelId": "mx_anywhere_2_ext3",
        "thumbnail": "/devices/thumbnails/mx_anywhere_2_ext3.png"
      },
      {
        "modelId": "mx_anywhere_2_ext1",
        "thumbnail": "/devices/thumbnails/mx_anywhere_2_ext1.png"
      },
      {
        "modelId": "mx_anywhere_2_ext2",
        "thumbnail": "/devices/thumbnails/mx_anywhere_2_ext2.png"
      },
      {
        "modelId": "mx_anywhere_2_ext3",
        "thumbnail": "/devices/thumbnails/mx_anywhere_2_ext3.png"
      }
    ]
  },
  "6b01f": {
    "modelId": "6b01f",
    "displayName": "MX Anywhere 2",
    "depot": "mx_anywhere_2_cr",
    "thumbnail": "/devices/thumbnails/mx_anywhere_2.png",
    "variants": []
  },
  "6b01a": {
    "modelId": "6b01a",
    "displayName": "MX Anywhere 2S",
    "depot": "mx_anywhere_2s",
    "thumbnail": "/devices/thumbnails/mx_anywhere_2s.png",
    "variants": [
      {
        "modelId": "mx_anywhere_2s_ext1",
        "thumbnail": "/devices/thumbnails/mx_anywhere_2s_ext1.png"
      },
      {
        "modelId": "mx_anywhere_2s_ext2",
        "thumbnail": "/devices/thumbnails/mx_anywhere_2s_ext2.png"
      },
      {
        "modelId": "mx_anywhere_2s_ext3",
        "thumbnail": "/devices/thumbnails/mx_anywhere_2s_ext3.png"
      },
      {
        "modelId": "mx_anywhere_2s_ext5",
        "thumbnail": "/devices/thumbnails/mx_anywhere_2s_ext5.png"
      },
      {
        "modelId": "mx_anywhere_2s_ext1",
        "thumbnail": "/devices/thumbnails/mx_anywhere_2s_ext1.png"
      },
      {
        "modelId": "mx_anywhere_2s_ext2",
        "thumbnail": "/devices/thumbnails/mx_anywhere_2s_ext2.png"
      },
      {
        "modelId": "mx_anywhere_2s_ext3",
        "thumbnail": "/devices/thumbnails/mx_anywhere_2s_ext3.png"
      },
      {
        "modelId": "mx_anywhere_2s_ext5",
        "thumbnail": "/devices/thumbnails/mx_anywhere_2s_ext5.png"
      }
    ]
  },
  "6b019": {
    "modelId": "6b019",
    "displayName": "MX Master 2S",
    "depot": "mx_master_2s",
    "thumbnail": "/devices/thumbnails/mx_master_2s.png",
    "variants": [
      {
        "modelId": "mx_master_2s_ext1",
        "thumbnail": "/devices/thumbnails/mx_master_2s_ext1.png"
      },
      {
        "modelId": "mx_master_2s_ext2",
        "thumbnail": "/devices/thumbnails/mx_master_2s_ext2.png"
      },
      {
        "modelId": "mx_master_2s_ext3",
        "thumbnail": "/devices/thumbnails/mx_master_2s_ext3.png"
      },
      {
        "modelId": "mx_master_2s_ext1",
        "thumbnail": "/devices/thumbnails/mx_master_2s_ext1.png"
      },
      {
        "modelId": "mx_master_2s_ext2",
        "thumbnail": "/devices/thumbnails/mx_master_2s_ext2.png"
      },
      {
        "modelId": "mx_master_2s_ext3",
        "thumbnail": "/devices/thumbnails/mx_master_2s_ext3.png"
      }
    ]
  },
  "8c093": {
    "modelId": "8c093",
    "displayName": "M500s",
    "depot": "m500s",
    "thumbnail": "/devices/thumbnails/m500s.png",
    "variants": []
  },
  "6b01b": {
    "modelId": "6b01b",
    "displayName": "M585/M590",
    "depot": "m585",
    "thumbnail": "/devices/thumbnails/m585.png",
    "variants": [
      {
        "modelId": "m585_ext1",
        "thumbnail": "/devices/thumbnails/m585_ext1.png"
      },
      {
        "modelId": "m585_ext2",
        "thumbnail": "/devices/thumbnails/m585_ext2.png"
      },
      {
        "modelId": "m585_ext3",
        "thumbnail": "/devices/thumbnails/m585_ext3.png"
      },
      {
        "modelId": "m585_ext4",
        "thumbnail": "/devices/thumbnails/m585_ext4.png"
      },
      {
        "modelId": "m585_ext5",
        "thumbnail": "/devices/thumbnails/m585_ext5.png"
      },
      {
        "modelId": "m585_ext1",
        "thumbnail": "/devices/thumbnails/m585_ext1.png"
      },
      {
        "modelId": "m585_ext2",
        "thumbnail": "/devices/thumbnails/m585_ext2.png"
      },
      {
        "modelId": "m585_ext3",
        "thumbnail": "/devices/thumbnails/m585_ext3.png"
      },
      {
        "modelId": "m585_ext4",
        "thumbnail": "/devices/thumbnails/m585_ext4.png"
      },
      {
        "modelId": "m585_ext5",
        "thumbnail": "/devices/thumbnails/m585_ext5.png"
      }
    ]
  },
  "44052": {
    "modelId": "44052",
    "displayName": "M545/M546",
    "depot": "m545_m546",
    "thumbnail": "/devices/thumbnails/m545.png",
    "variants": []
  },
  "44094": {
    "modelId": "44094",
    "displayName": "M325",
    "depot": "m325",
    "thumbnail": "/devices/thumbnails/m325.png",
    "variants": []
  },
  "6b012": {
    "modelId": "6b012",
    "displayName": "MX Master",
    "depot": "mx_master",
    "thumbnail": "/devices/thumbnails/mx_master.png",
    "variants": []
  },
  "6b01e": {
    "modelId": "6b01e",
    "displayName": "MX Master",
    "depot": "mx_master_cr",
    "thumbnail": "/devices/thumbnails/mx_master.png",
    "variants": [
      {
        "modelId": "mx_master_cr_ext3",
        "thumbnail": "/devices/thumbnails/mx_master_cr_ext3.png"
      },
      {
        "modelId": "mx_master_cr_ext3",
        "thumbnail": "/devices/thumbnails/mx_master_cr_ext3.png"
      }
    ]
  },
  "6b017": {
    "modelId": "6b017",
    "displayName": "MX Master",
    "depot": "mx_master_restage",
    "thumbnail": "/devices/thumbnails/mx_master.png",
    "variants": [
      {
        "modelId": "mx_master_restage_ext1",
        "thumbnail": "/devices/thumbnails/mx_master_restage_ext1.png"
      },
      {
        "modelId": "mx_master_restage_ext2",
        "thumbnail": "/devices/thumbnails/mx_master_restage_ext2.png"
      },
      {
        "modelId": "mx_master_restage_ext1",
        "thumbnail": "/devices/thumbnails/mx_master_restage_ext1.png"
      },
      {
        "modelId": "mx_master_restage_ext2",
        "thumbnail": "/devices/thumbnails/mx_master_restage_ext2.png"
      }
    ]
  },
  "6b34c": {
    "modelId": "6b34c",
    "displayName": "K370s/K375s",
    "depot": "k375s",
    "thumbnail": "/devices/thumbnails/k375s.png",
    "variants": []
  },
  "8c900": {
    "modelId": "8c900",
    "displayName": "Litra Glow",
    "depot": "litra_glow",
    "thumbnail": "/devices/thumbnails/litra_glow.png",
    "variants": []
  },
  "8c901": {
    "modelId": "8c901",
    "displayName": "Litra Beam",
    "depot": "litra_beam",
    "thumbnail": "/devices/thumbnails/litra_beam.png",
    "variants": []
  },
  "6b33b": {
    "modelId": "6b33b",
    "displayName": "K780",
    "depot": "k780",
    "thumbnail": "/devices/thumbnails/k780.png",
    "variants": []
  },
  "1b016": {
    "modelId": "1b016",
    "displayName": "M336 / M337 / M535",
    "depot": "m337",
    "thumbnail": "/devices/thumbnails/m337.png",
    "variants": []
  },
  "44050": {
    "modelId": "44050",
    "displayName": "M335",
    "depot": "m335",
    "thumbnail": "/devices/thumbnails/m335.png",
    "variants": []
  },
  "1b014": {
    "modelId": "1b014",
    "displayName": "M336/M337/M535",
    "depot": "m336",
    "thumbnail": "/devices/thumbnails/m337.png",
    "variants": []
  },
  "4075": {
    "modelId": "4075",
    "displayName": "Wireless Keyboard",
    "depot": "k470",
    "thumbnail": "/devices/thumbnails/generic-keyboard.png",
    "variants": []
  },
  "8c33b": {
    "modelId": "8c33b",
    "displayName": "K840",
    "depot": "k840",
    "thumbnail": "/devices/thumbnails/k840.png",
    "variants": []
  },
  "1b33d": {
    "modelId": "1b33d",
    "displayName": "K480",
    "depot": "k480",
    "thumbnail": "/devices/thumbnails/k480.png",
    "variants": []
  },
  "4406e": {
    "modelId": "4406e",
    "displayName": "K800",
    "depot": "k800",
    "thumbnail": "/devices/thumbnails/k800.png",
    "variants": [
      {
        "modelId": "k800_ext1",
        "thumbnail": "/devices/thumbnails/k800_ext1.png"
      }
    ]
  },
  "6b353": {
    "modelId": "6b353",
    "displayName": "K600 TV",
    "depot": "k600",
    "thumbnail": "/devices/thumbnails/k600.png",
    "variants": []
  },
  "6b335": {
    "modelId": "6b335",
    "displayName": "K830",
    "depot": "k830",
    "thumbnail": "/devices/thumbnails/k830.png",
    "variants": []
  },
  "4032": {
    "modelId": "4032",
    "displayName": "K830",
    "depot": "k830_4032",
    "thumbnail": "/devices/thumbnails/k830_4032.png",
    "variants": []
  },
  "4404d": {
    "modelId": "4404d",
    "displayName": "K400 Plus",
    "depot": "k400_plus",
    "thumbnail": "/devices/thumbnails/k400_plus.png",
    "variants": []
  },
  "44068": {
    "modelId": "44068",
    "displayName": "K400 Professional",
    "depot": "k400_pro",
    "thumbnail": "/devices/thumbnails/k400.png",
    "variants": []
  },
  "4101b": {
    "modelId": "4101b",
    "displayName": "M705",
    "depot": "m705_lcc",
    "thumbnail": "/devices/thumbnails/m705_lcc.png",
    "variants": [
      {
        "modelId": "m705_lcc_ext1",
        "thumbnail": "/devices/thumbnails/m705_lcc_ext1.png"
      }
    ]
  },
  "4406d": {
    "modelId": "4406d",
    "displayName": "M705",
    "depot": "m705",
    "thumbnail": "/devices/thumbnails/m705.png",
    "variants": [
      {
        "modelId": "m705_ext1",
        "thumbnail": "/devices/thumbnails/m705_ext1.png"
      }
    ]
  },
  "41017": {
    "modelId": "41017",
    "displayName": "MX Anywhere",
    "depot": "mx_anywhere",
    "thumbnail": "/devices/thumbnails/mx_anywhere.png",
    "variants": []
  },
  "41028": {
    "modelId": "41028",
    "displayName": "M570",
    "depot": "m570",
    "thumbnail": "/devices/thumbnails/m570.png",
    "variants": []
  },
  "0825": {
    "modelId": "0825",
    "displayName": "C270",
    "depot": "c270",
    "thumbnail": "/devices/thumbnails/c270.png",
    "variants": []
  },
  "0917": {
    "modelId": "0917",
    "displayName": "Brio 305",
    "depot": "brio_3xx",
    "thumbnail": null,
    "variants": [
      {
        "modelId": "brio_3xx_ext1",
        "thumbnail": "/devices/thumbnails/brio_3xx_ext1.png"
      },
      {
        "modelId": "brio_3xx_ext2",
        "thumbnail": "/devices/thumbnails/brio_3xx_ext2.png"
      },
      {
        "modelId": "brio_3xx_ext3",
        "thumbnail": "/devices/thumbnails/brio_3xx_ext3.png"
      },
      {
        "modelId": "brio_3xx_ext7",
        "thumbnail": "/devices/thumbnails/brio_3xx_ext7.png"
      },
      {
        "modelId": "brio_3xx_ext1",
        "thumbnail": "/devices/thumbnails/brio_3xx_ext1.png"
      }
    ]
  },
  "085b": {
    "modelId": "085b",
    "displayName": "C925e",
    "depot": "c925e",
    "thumbnail": "/devices/thumbnails/c925e.png",
    "variants": []
  },
  "0883": {
    "modelId": "0883",
    "displayName": "C922",
    "depot": "c922",
    "thumbnail": "/devices/thumbnails/c922.png",
    "variants": []
  },
  "082d": {
    "modelId": "082d",
    "displayName": "C920",
    "depot": "c920",
    "thumbnail": "/devices/thumbnails/c920.png",
    "variants": []
  },
  "08e7": {
    "modelId": "08e7",
    "displayName": "C920e",
    "depot": "c920e",
    "thumbnail": "/devices/thumbnails/c920e.png",
    "variants": []
  },
  "08b7": {
    "modelId": "08b7",
    "displayName": "C920c",
    "depot": "c920c",
    "thumbnail": "/devices/thumbnails/c920c.png",
    "variants": []
  },
  "091b": {
    "modelId": "091b",
    "displayName": "C930s",
    "depot": "c930s",
    "thumbnail": "/devices/thumbnails/c930s.png",
    "variants": []
  },
  "091c": {
    "modelId": "091c",
    "displayName": "C930n",
    "depot": "c930n",
    "thumbnail": "/devices/thumbnails/c930n.png",
    "variants": []
  },
  "0843": {
    "modelId": "0843",
    "displayName": "C930e",
    "depot": "c930e",
    "thumbnail": "/devices/thumbnails/c930e.png",
    "variants": []
  },
  "0891": {
    "modelId": "0891",
    "displayName": "C930c",
    "depot": "c930c",
    "thumbnail": "/devices/thumbnails/c930c.png",
    "variants": []
  },
  "4101a": {
    "modelId": "4101a",
    "displayName": "Performance MX",
    "depot": "performance_mx",
    "thumbnail": "/devices/thumbnails/performance_mx.png",
    "variants": []
  },
  "6b503": {
    "modelId": "6b503",
    "displayName": "Spotlight",
    "depot": "spotlight",
    "thumbnail": "/devices/thumbnails/spotlight.png",
    "variants": [
      {
        "modelId": "spotlight_ext1",
        "thumbnail": "/devices/thumbnails/spotlight_ext1.png"
      },
      {
        "modelId": "spotlight_ext2",
        "thumbnail": "/devices/thumbnails/spotlight_ext2.png"
      },
      {
        "modelId": "spotlight_ext6",
        "thumbnail": "/devices/thumbnails/spotlight_ext6.png"
      },
      {
        "modelId": "spotlight_ext7",
        "thumbnail": "/devices/thumbnails/spotlight_ext7.png"
      },
      {
        "modelId": "spotlight_ext1",
        "thumbnail": "/devices/thumbnails/spotlight_ext1.png"
      },
      {
        "modelId": "spotlight_ext2",
        "thumbnail": "/devices/thumbnails/spotlight_ext2.png"
      },
      {
        "modelId": "spotlight_ext6",
        "thumbnail": "/devices/thumbnails/spotlight_ext6.png"
      },
      {
        "modelId": "spotlight_ext7",
        "thumbnail": "/devices/thumbnails/spotlight_ext7.png"
      }
    ]
  },
  "10000001": {
    "modelId": "10000001",
    "displayName": "Software events",
    "depot": "software_events_virtual_device",
    "thumbnail": null,
    "variants": []
  },
  "c53e": {
    "modelId": "c53e",
    "displayName": "Logi Spotlight Receiver",
    "depot": "c53e",
    "thumbnail": null,
    "variants": []
  },
  "6b505": {
    "modelId": "6b505",
    "displayName": "R500",
    "depot": "r500_r500s",
    "thumbnail": "/devices/thumbnails/r500.png",
    "variants": [
      {
        "modelId": "r500_ext1",
        "thumbnail": "/devices/thumbnails/r500_ext1.png"
      },
      {
        "modelId": "r500_ext2",
        "thumbnail": "/devices/thumbnails/r500_ext2.png"
      },
      {
        "modelId": "r500_ext3",
        "thumbnail": "/devices/thumbnails/r500_ext3.png"
      },
      {
        "modelId": "r500_ext1",
        "thumbnail": "/devices/thumbnails/r500_ext1.png"
      },
      {
        "modelId": "r500_ext2",
        "thumbnail": "/devices/thumbnails/r500_ext2.png"
      },
      {
        "modelId": "r500_ext3",
        "thumbnail": "/devices/thumbnails/r500_ext3.png"
      }
    ]
  },
  "c540": {
    "modelId": "c540",
    "displayName": "Logi R500 Receiver",
    "depot": "c540",
    "thumbnail": null,
    "variants": []
  },
  "085e": {
    "modelId": "085e",
    "displayName": "Brio",
    "depot": "brio",
    "thumbnail": "/devices/thumbnails/brio.png",
    "variants": []
  },
  "086b": {
    "modelId": "086b",
    "displayName": "Brio 4k Stream",
    "depot": "brio_4k",
    "thumbnail": "/devices/thumbnails/brio_4k.png",
    "variants": []
  },
  "0919": {
    "modelId": "0919",
    "displayName": "Brio 505",
    "depot": "brio_505",
    "thumbnail": null,
    "variants": [
      {
        "modelId": "brio_505_ext1",
        "thumbnail": "/devices/thumbnails/brio_505_ext1.png"
      },
      {
        "modelId": "brio_505_ext2",
        "thumbnail": "/devices/thumbnails/brio_505_ext2.png"
      },
      {
        "modelId": "brio_505_ext3",
        "thumbnail": "/devices/thumbnails/brio_505_ext3.png"
      },
      {
        "modelId": "brio_505_ext1",
        "thumbnail": "/devices/thumbnails/brio_505_ext1.png"
      }
    ]
  },
  "0943": {
    "modelId": "0943",
    "displayName": "Brio 500",
    "depot": "brio_500",
    "thumbnail": null,
    "variants": [
      {
        "modelId": "brio_500_ext1",
        "thumbnail": "/devices/thumbnails/brio_500_ext1.png"
      },
      {
        "modelId": "brio_500_ext2",
        "thumbnail": "/devices/thumbnails/brio_500_ext2.png"
      },
      {
        "modelId": "brio_500_ext3",
        "thumbnail": "/devices/thumbnails/brio_500_ext3.png"
      },
      {
        "modelId": "brio_500_ext1",
        "thumbnail": "/devices/thumbnails/brio_500_ext1.png"
      }
    ]
  },
  "0946": {
    "modelId": "0946",
    "displayName": "Brio 501",
    "depot": "brio_501",
    "thumbnail": null,
    "variants": [
      {
        "modelId": "brio_501_ext1",
        "thumbnail": "/devices/thumbnails/brio_501_ext1.png"
      },
      {
        "modelId": "brio_501_ext1",
        "thumbnail": "/devices/thumbnails/brio_501_ext1.png"
      }
    ]
  },
  "0893": {
    "modelId": "0893",
    "displayName": "StreamCam",
    "depot": "streamcam",
    "thumbnail": null,
    "variants": [
      {
        "modelId": "streamcam_ext1",
        "thumbnail": "/devices/thumbnails/streamcam_ext1.png"
      },
      {
        "modelId": "streamcam_ext2",
        "thumbnail": "/devices/thumbnails/streamcam_ext2.png"
      },
      {
        "modelId": "streamcam_ext1",
        "thumbnail": "/devices/thumbnails/streamcam_ext1.png"
      }
    ]
  },
  "0948": {
    "modelId": "0948",
    "displayName": "Reach",
    "depot": "reach",
    "thumbnail": "/devices/thumbnails/reach.png",
    "variants": []
  },
  "2b37f": {
    "modelId": "2b37f",
    "displayName": "K370 for Business",
    "depot": "d172c429-6eb7-4c2f-b52e-73be21d1adad",
    "thumbnail": null,
    "variants": []
  },
  "2b03b": {
    "modelId": "2b03b",
    "displayName": "M240 Silent for Business",
    "depot": "e190fefb-4b37-4557-96f6-fbd57f0d80ba",
    "thumbnail": null,
    "variants": []
  },
  "2b03a": {
    "modelId": "2b03a",
    "displayName": "M240 Silent",
    "depot": "760a0d12-4016-465a-94cc-51b4826eee39",
    "thumbnail": null,
    "variants": []
  },
  "2b381": {
    "modelId": "2b381",
    "displayName": "Signature K865",
    "depot": "a4896684-4639-4d1a-9a54-05728dca7f47",
    "thumbnail": null,
    "variants": []
  },
  "2b378": {
    "modelId": "2b378",
    "displayName": "MX Keys S",
    "depot": "c097f928-2718-4125-ade5-15d1b39c3f60",
    "thumbnail": null,
    "variants": []
  },
  "2b380": {
    "modelId": "2b380",
    "displayName": "MX Keys for business",
    "depot": "5d1fbaaf-3f0a-44bf-a874-3ca085073f66",
    "thumbnail": null,
    "variants": []
  },
  "2b37c": {
    "modelId": "2b37c",
    "displayName": "MX Keys S for Mac",
    "depot": "efab3873-8c16-4e9f-a2e4-f353448c31ea",
    "thumbnail": null,
    "variants": []
  },
  "2b037": {
    "modelId": "2b037",
    "displayName": "MX Anywhere 3S",
    "depot": "5d30ec43-b3f7-45e9-8a86-d5d087a27682",
    "thumbnail": null,
    "variants": []
  },
  "2b038": {
    "modelId": "2b038",
    "displayName": "MX Anywhere 3S for Business",
    "depot": "8583f89a-6654-4f8e-aeee-7ff020fc2e8c",
    "thumbnail": null,
    "variants": []
  },
  "2b036": {
    "modelId": "2b036",
    "displayName": "Pebble Mouse 2 M350s",
    "depot": "e6e5ba46-9869-11ed-93af-9b54b65e3514",
    "thumbnail": null,
    "variants": []
  },
  "2b377": {
    "modelId": "2b377",
    "displayName": "Pebble Keys 2 K380s",
    "depot": "ffa457d6-9869-11ed-adf4-37f8415113ce",
    "thumbnail": null,
    "variants": []
  },
  "2b379": {
    "modelId": "2b379",
    "displayName": "Pebble Keys 2 K390 for Mac",
    "depot": "ffa458c6-9869-11ed-adf5-b7bf848fb999",
    "thumbnail": null,
    "variants": []
  },
  "2b385": {
    "modelId": "2b385",
    "displayName": "Wave Keys for Mac",
    "depot": "cba04d37-8016-43aa-819a-04316bc90f4d",
    "thumbnail": null,
    "variants": []
  },
  "2b383": {
    "modelId": "2b383",
    "displayName": "Wave Keys",
    "depot": "04a827ee-fa8a-4f96-88aa-3eb321f20f7e",
    "thumbnail": null,
    "variants": []
  },
  "2bb00": {
    "modelId": "2bb00",
    "displayName": "Casa Touch",
    "depot": "a817dc42-9c9a-11ed-a8fc-0242ac120002",
    "thumbnail": null,
    "variants": []
  },
  "2bb01": {
    "modelId": "2bb01",
    "displayName": "Pop-Up Touch for Business",
    "depot": "411531c2-9883-11ed-a8fc-0242ac120002",
    "thumbnail": null,
    "variants": []
  },
  "2b371": {
    "modelId": "2b371",
    "displayName": "Casa Keys",
    "depot": "dcd5ad10-9c9a-11ed-a8fc-0242ac120002",
    "thumbnail": null,
    "variants": []
  },
  "2b374": {
    "modelId": "2b374",
    "displayName": "Pop-Up Keys for Business",
    "depot": "bc1c2378-9c9b-11ed-a8fc-0242ac120002",
    "thumbnail": null,
    "variants": []
  },
  "2b384": {
    "modelId": "2b384",
    "displayName": "Wave Keys for Business",
    "depot": "030391ea-323d-487a-8a5a-538b11e6112b",
    "thumbnail": null,
    "variants": []
  },
  "10000000": {
    "modelId": "10000000",
    "displayName": "Actions Ring",
    "depot": "88b73d28-24d8-47bd-84a2-c45cad5640d3",
    "thumbnail": null,
    "variants": []
  },
  "2b386": {
    "modelId": "2b386",
    "displayName": "Signature Slim K950",
    "depot": "14b9f52a-1bd1-4137-a04c-5a130de5b4af",
    "thumbnail": null,
    "variants": []
  },
  "2b388": {
    "modelId": "2b388",
    "displayName": "Signature Slim K950 for Business",
    "depot": "14056517-b0bd-4cd6-bd00-fe74f2d51179",
    "thumbnail": null,
    "variants": []
  },
  "8c354": {
    "modelId": "8c354",
    "displayName": "MX Creative Keypad",
    "depot": "7ff8f5fe-c263-11ed-a0c5-325096b39f47",
    "thumbnail": null,
    "variants": []
  },
  "2bc00": {
    "modelId": "2bc00",
    "displayName": "MX Creative Dialpad",
    "depot": "3348402c-d6c2-42e1-afb8-f129275647aa",
    "thumbnail": null,
    "variants": []
  },
  "0949": {
    "modelId": "0949",
    "displayName": "Brio 90",
    "depot": "915d6c56-e268-4cde-8d74-1f8b936e41f6",
    "thumbnail": null,
    "variants": []
  },
  "094a": {
    "modelId": "094a",
    "displayName": "Brio 95 for Business",
    "depot": "5b7d18a6-eef7-4fed-9448-571dcd0e0718",
    "thumbnail": null,
    "variants": []
  },
  "094c": {
    "modelId": "094c",
    "displayName": "Brio 100",
    "depot": "81fd3fde-3da2-464e-9c41-768f32a00f76",
    "thumbnail": null,
    "variants": []
  },
  "094d": {
    "modelId": "094d",
    "displayName": "Brio 101",
    "depot": "39d71f7b-8b8f-4253-a702-be66ca2e99a7",
    "thumbnail": null,
    "variants": []
  },
  "094b": {
    "modelId": "094b",
    "displayName": "Brio 105 for Business",
    "depot": "d8cb42a2-d48d-42ba-a5b2-9d64cd4a9ef0",
    "thumbnail": null,
    "variants": []
  },
  "0944": {
    "modelId": "0944",
    "displayName": "MX Brio",
    "depot": "15f653ce-7c30-4c9e-9daf-2e4833f04f73",
    "thumbnail": null,
    "variants": []
  },
  "091d": {
    "modelId": "091d",
    "displayName": "MX Brio 705 for Business",
    "depot": "07757dc5-cb9d-4931-a8e1-e81ea3e263e1",
    "thumbnail": null,
    "variants": []
  },
  "2b03d": {
    "modelId": "2b03d",
    "displayName": "Signature Plus M750 L For Business",
    "depot": "c6df3179-10f0-4ecf-b8d1-df7743a5fc00",
    "thumbnail": null,
    "variants": []
  },
  "2b03e": {
    "modelId": "2b03e",
    "displayName": "MX Ergo S",
    "depot": "924b0645-1c6a-48ee-94ce-00591467404c",
    "thumbnail": null,
    "variants": []
  },
  "2b38c": {
    "modelId": "2b38c",
    "displayName": "Keys-To-Go 2",
    "depot": "0e035a79-730a-41ac-85f4-c51bfaff8a72",
    "thumbnail": null,
    "variants": []
  },
  "2b38d": {
    "modelId": "2b38d",
    "displayName": "Keys-To-Go 2",
    "depot": "16aef976-a03c-44f3-a5db-9c6443bf8570",
    "thumbnail": null,
    "variants": []
  },
  "2b040": {
    "modelId": "2b040",
    "displayName": "Signature AI Edition M750",
    "depot": "2cf9a81d-47cb-4736-9bc0-39e3143d71d3",
    "thumbnail": null,
    "variants": []
  },
  "2b38f": {
    "modelId": "2b38f",
    "displayName": "POP Icon Keys",
    "depot": "2fa9a1ae-1b69-4cd5-bd29-174a1ebab914",
    "thumbnail": null,
    "variants": []
  },
  "2b38e": {
    "modelId": "2b38e",
    "displayName": "Alto Keys K98M",
    "depot": "2dbc7b2a-4334-409f-b9f3-48349591ad00",
    "thumbnail": null,
    "variants": []
  },
  "2b041": {
    "modelId": "2b041",
    "displayName": "ERGO M575S Trackball",
    "depot": "e93f22c4-fca9-4bcd-a756-33bcd09d6a79",
    "thumbnail": null,
    "variants": []
  },
  "2b395": {
    "modelId": "2b395",
    "displayName": "Signature Slim K950 for Business Copilot Edition",
    "depot": "e4fd2f36-49cf-46f7-ad70-97c5bcdf8eb8",
    "thumbnail": null,
    "variants": []
  },
  "2b391": {
    "modelId": "2b391",
    "displayName": "Signature Slim Solar+",
    "depot": "978242a5-cddb-4d69-bcb3-cef516007f9d",
    "thumbnail": null,
    "variants": []
  },
  "2b392": {
    "modelId": "2b392",
    "displayName": "Signature Slim Solar+ for Mac",
    "depot": "4879e5ef-01b9-4d68-8690-15a276fef348",
    "thumbnail": null,
    "variants": []
  },
  "2b394": {
    "modelId": "2b394",
    "displayName": "Signature Slim Solar+ K980 for Business",
    "depot": "44884ec4-d6c2-4579-bc06-c2c75fad1ab1",
    "thumbnail": null,
    "variants": []
  },
  "2b042": {
    "modelId": "2b042",
    "displayName": "MX Master 4",
    "depot": "2334eaeb-eeeb-4249-abfd-67002f421230",
    "thumbnail": null,
    "variants": []
  },
  "2b048": {
    "modelId": "2b048",
    "displayName": "MX Master 4 for Business",
    "depot": "49a3cbfc-6157-4d84-b165-370086b0d455",
    "thumbnail": null,
    "variants": []
  },
  "2b396": {
    "modelId": "2b396",
    "displayName": "Alto Keys K75M",
    "depot": "0625d7ab-68d0-4622-b01e-a3fd806530d7",
    "thumbnail": null,
    "variants": []
  },
  "8c35d": {
    "modelId": "8c35d",
    "displayName": "Signature Slim Wired K620 for Business",
    "depot": "fe01b978-fbab-4e7c-841f-01d41c99163d",
    "thumbnail": null,
    "variants": []
  },
  "8c0a2": {
    "modelId": "8c0a2",
    "displayName": "Signature Wired M520 L for Business",
    "depot": "5bf3bbb2-8e4e-4d33-a0b3-1c010ece1afc",
    "thumbnail": null,
    "variants": []
  },
  "2b398": {
    "modelId": "2b398",
    "displayName": "Flip Folio",
    "depot": "c291e5a1-58e8-40a0-8cfe-141160df0ac5",
    "thumbnail": null,
    "variants": []
  },
  "2b399": {
    "modelId": "2b399",
    "displayName": "Flip Folio",
    "depot": "564a3417-e7d2-477d-b648-59ace1d4b45e",
    "thumbnail": null,
    "variants": []
  },
  "ab39a": {
    "modelId": "ab39a",
    "displayName": "Signature Mechanical K868",
    "depot": "1a65c02e-bfbf-49e8-86fd-bf7ece635350",
    "thumbnail": null,
    "variants": []
  },
  "8c362": {
    "modelId": "8c362",
    "displayName": "Signature Mechanical K848",
    "depot": "3e826a89-b536-4e85-aa26-e891b62199d4",
    "thumbnail": null,
    "variants": []
  }
};
